image:
    raw: true
    preset:
        - 480*480
        - 1080*1080

http:
    host: 0.0.0.0
    port: 9779
    cert: cert.pem
    key: key.pem
    tls: false

storage:
    type: minio
    path: ./gallery
    endpoint: 127.0.0.1:9000
    bucket: gallery
    accessKey: "12345678"
    secretKey: "12345678"
    tls: false

dev: true
